name: webhook_manager
description: A new Flutter project.
# TODO: Android google service integration pending

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  http: ^0.12.0+4
  rxdart: ^0.24.0
  sentry: ^3.0.1
  catcher: ^0.3.4
  sqflite: ^1.3.0
  google_fonts: ^0.5.0+1
  firebase_auth: ^0.16.0
  flutter_slidable: ^0.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/

dev_dependencies:
