name: webhook_manager
description: A new Flutter project.
# TODO: Android google service integration pending

version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1
  http: ^0.12.0+4
  sentry: ^3.0.1
  catcher: ^0.3.2
  sqflite: ^1.3.0
  firebase_auth: ^0.16.0
  google_fonts: ^0.3.10
  intl: ^0.16.1

flutter:
  uses-material-design: true
  assets:
    - assets/
